spring:
    datasource:
        url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
        username: ${PG_USERNAME}
        password: ${PG_PASSWORD}
    jpa:
        hibernate:
            ddl-auto: update
    main:
        allow-circular-references: true