@startuml
class barbershop.configs.Config {
+ SpringSecurityDialect springSecurityDialect()
}
class barbershop.configs.SecurityConfig {
- UserService userService
# void configure(HttpSecurity)
+ BCryptPasswordEncoder bCryptPasswordEncoder()
# void configureGlobal(AuthenticationManagerBuilder)
}


org.springframework.security.config.annotation.web.configuration.WebSecurityConfigurerAdapter <|-- barbershop.configs.SecurityConfig
@enduml