@startuml
class barbershop.dao.entity.Role {
- Long id
- String name
+ <<Create>> Role()
+ <<Create>> Role(Long,String)
}
class barbershop.dao.entity.UserRegistration {
- String password
- String login
- Boolean terms
}
class barbershop.dao.entity.User {
- long id
- String login
- String password
- String sessionID
- Collection<Role> roles
- List<Book> books
+ <<Create>> User()
+ <<Create>> User(String,String)
+ <<Create>> User(String,Collection<Role>)
+ void addBook(Book)
+ void removeBook(Book)
}
class barbershop.dao.entity.Book {
- Long id
~ String category
~ String name
~ String image
~ String author
~ int price
~ String description
~ int quantity
- Set<User> baskets
}
interface barbershop.dao.repos.UserRepository {
~ User getByLogin(String)
}
interface barbershop.dao.repos.BookRepository {
~ List<Book> getAllByCategory(String)
~ Book getByName(String)
}


org.springframework.data.jpa.repository.JpaRepository <|-- barbershop.dao.repos.UserRepository
org.springframework.data.jpa.repository.JpaRepository <|-- barbershop.dao.repos.BookRepository
barbershop.dao.entity.User --o barbershop.dao.entity.Book
barbershop.dao.entity.User --o barbershop.dao.entity.Role
barbershop.dao.repos.UserRepository --o barbershop.dao.entity.User
barbershop.dao.repos.BookRepository --o barbershop.dao.entity.Book
@enduml